include: package:flutter_lints/flutter.yaml
analyzer:
  exclude: ["**/*.g.dart", "**/*.freezed.dart", lib/generated/**, mason/**]
  # plugins:
    # - custom_lint
    
linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
